apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  name: qwen2-05b-instruct-single
  annotations: 
    security.opendatahub.io/enable-auth: 'false'
spec:
  model:
    uri: hf://Qwen/Qwen2.5-0.5B-Instruct
    name: Qwen/Qwen2.5-0.5B-Instruct
  replicas: 1
  router:
    scheduler: { }  # Default scheduler with default load balancing
    route: { }
    gateway: { }
  template:
    containers:
      - name: main
        resources:
          limits:
            cpu: '2'
            memory: 10Gi
            nvidia.com/gpu: "1"
          requests:
            cpu: '1'
            memory: 10Gi
            nvidia.com/gpu: "1"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
            scheme: HTTPS
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 30
          failureThreshold: 5