apiVersion: apps/v1
kind: Deployment
metadata:
  name: chunker-service
  labels:
    app: chunker-service
    app.kubernetes.io/name: chunker-service
    app.kubernetes.io/component: chunker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chunker-service
  template:
    metadata:
      labels:
        app: chunker-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8085"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: chunker
        image: quay.io/rh-ee-mmisiura/chunkers:trial_0
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
          name: grpc
          protocol: TCP
        livenessProbe:
          grpc:
            port: 8085
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          grpc:
            port: 8085
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        env:
        - name: LOG_LEVEL
          value: "INFO"
---
apiVersion: v1
kind: Service
metadata:
  name: chunker-service
  labels:
    app: chunker-service
spec:
  selector:
    app: chunker-service
  ports:
  - port: 8085
    targetPort: 8085
    protocol: TCP
    name: grpc
  type: ClusterIP